package ru.novolmob.backendapi.repositories

import ru.novolmob.backendapi.models.OrderToDeviceEntityCreateModel
import ru.novolmob.backendapi.models.OrderToDeviceEntityModel
import ru.novolmob.backendapi.models.OrderToDeviceEntityUpdateModel
import ru.novolmob.database.models.ids.OrderToDeviceEntityId

interface IOrderToDeviceRepository: ICrudRepository<OrderToDeviceEntityId, OrderToDeviceEntityModel, OrderToDeviceEntityCreateModel, OrderToDeviceEntityUpdateModel>